import React from 'react';
// import logo from '@/public/images/logo.jpg'
import logo from '@/public/images/logo.jpg'
import Head from 'next/head';
function Headhtml(props) {
    return (
        <Head>
            <title>Top Nepal</title>  

            {/* meta seo */}
            <meta name="description" content="Generated by create next app" />
            <meta name="description" content="Top Nepal Treks & Tours" />
            <meta name="title" content="Top Nepal Treks & Tours - Du lịch trekking Nepal"/>
            <meta name="description" content="Top Nepal Treks & Tours cung cấp các chuyến đi trekking tại Nepal với các gói tour hấp dẫn, đội ngũ hướng dẫn chuyên nghiệp và dịch vụ chất lượng. Đặt tour của bạn ngay hôm nay!"></meta>
            <meta name="description" content="Top Nepal Treks & Tours offers trekking tours in Nepal with attractive tour packages, professional guide team, and quality services. Book your tour today!"></meta>
            <meta name="keywords" content="Top Nepal Treks & Tours, trekking Nepal, trekking tours, du lịch trekking, du lịch Nepal"></meta>
            <meta name="keywords" content="Top Nepal Treks & Tours, Nepal trekking, trekking tours, trekking travel, Nepal travel"></meta>
            <meta name="viewport" content="width=device-width, initial-scale=1" />

            {/* meta preview link https://img.freepik.com/free-vector/beautiful-hand-draw-landscape-with-mountain-sketch-design_1035-20277.jpg?w=900&t=st=1680976563~exp=1680977163~hmac=c104c53e79636b2a3cb24657ccd2b4e1baed64cfa775ce36a1f4c6feb4448440 */}
            <meta property="og:image" content={logo} />
            <meta property="og:title" content="Top Nepal Treks & Tours || Trekking Tours in Nepal with Professional Guides"/>
            <meta property="og:description" content="Top Nepal Treks & Tours provides trekking tours in Nepal with attractive packages, professional guides, and quality services. Book your tour today!"/>

            <link rel="icon" href="/images/logo.jpg" />
            
        </Head>
    );
}

export default Headhtml;